[dependencies]
alloc = {  }
sgx_types = { path = "../../deps/incubator-teaclave-sgx-sdk/sgx_types", stage = 1 }
sgx_alloc = { path = "../../deps/incubator-teaclave-sgx-sdk/sgx_alloc", stage = 1 }
sgx_unwind = { path = "../../deps/incubator-teaclave-sgx-sdk/sgx_unwind", stage = 1 }
sgx_demangle = { path = "../../deps/incubator-teaclave-sgx-sdk/sgx_demangle", stage = 1 }
panic_abort = { path = "../../deps/incubator-teaclave-sgx-sdk/sgx_panic_abort", stage = 1 }
sgx_libc = { path = "../../deps/incubator-teaclave-sgx-sdk/sgx_libc", stage = 2 }
sgx_tkey_exchange = { path = "../../deps/incubator-teaclave-sgx-sdk/sgx_tkey_exchange", stage = 2 }
sgx_tse = { path = "../../deps/incubator-teaclave-sgx-sdk/sgx_tse", stage = 2 }
sgx_tcrypto = { path = "../../deps/incubator-teaclave-sgx-sdk/sgx_tcrypto", stage = 2 }
sgx_trts = { path = "../../deps/incubator-teaclave-sgx-sdk/sgx_trts", stage = 3 }
sgx_backtrace_sys = { path = "../../deps/incubator-teaclave-sgx-sdk/sgx_backtrace_sys", stage = 3 }
panic_unwind = { path = "../../deps/incubator-teaclave-sgx-sdk/sgx_panic_unwind", stage = 3 }
sgx_tdh = { path = "../../deps/incubator-teaclave-sgx-sdk/sgx_tdh", stage = 4 }
sgx_tseal = { path = "../../deps/incubator-teaclave-sgx-sdk/sgx_tseal", stage = 4 }
sgx_tprotected_fs = { path = "../../deps/incubator-teaclave-sgx-sdk/sgx_tprotected_fs", stage = 4 }
std = { git = "https://github.com/apache/teaclave-sgx-sdk.git", rev = "c70a82f708fd20e9fd0377990dde097d14024f7a", stage = 5, features = [] }
sgx_no_tstd = { path = "../../deps/incubator-teaclave-sgx-sdk/sgx_no_tstd", stage = 5 }
sgx_rand = { path = "../../deps/incubator-teaclave-sgx-sdk/sgx_rand", stage = 6 }
sgx_serialize = { path = "../../deps/incubator-teaclave-sgx-sdk/sgx_serialize", stage = 6 }
sgx_tunittest = { path = "../../deps/incubator-teaclave-sgx-sdk/sgx_tunittest", stage = 6 }
sgx_backtrace = { path = "../../deps/incubator-teaclave-sgx-sdk/sgx_backtrace", stage = 7 }
sgx_cov = { path = "../../deps/incubator-teaclave-sgx-sdk/sgx_cov", stage = 7 }
sgx_signal = { path = "../../deps/incubator-teaclave-sgx-sdk/sgx_signal", stage = 7 }
