/* (c) 2019 Confio UO. Licensed under Apache-2.0 */

/* Generated with cbindgen:0.24.5 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

enum ErrnoValue {
  ErrnoValue_Success = 0,
  ErrnoValue_Other = 1,
  ErrnoValue_OutOfGas = 2,
};
typedef int32_t ErrnoValue;

/**
 * This enum gives names to the status codes returned from Go callbacks to Rust.
 *
 * The go code will return one of these variants when returning.
 *
 */
enum GoResult {
  GoResult_Ok = 0,
  /**
   * Go panicked for an unexpected reason.
   */
  GoResult_Panic = 1,
  /**
   * Go received a bad argument from Rust
   */
  GoResult_BadArgument = 2,
  /**
   * Ran out of gas while using the SDK (e.g. storage)
   */
  GoResult_OutOfGas = 3,
  /**
   * An error happened during normal operation of a Go callback, which should abort the contract
   */
  GoResult_Other = 4,
  /**
   * An error happened during normal operation of a Go callback, which should be fed back to the contract
   */
  GoResult_User = 5,
};
typedef int32_t GoResult;

typedef struct Buffer {
  uint8_t *ptr;
  uintptr_t len;
  uintptr_t cap;
} Buffer;

bool validate_random(struct Buffer random,
                     struct Buffer proof,
                     struct Buffer block_hash,
                     uint64_t height);

struct Buffer get_random_number(struct Buffer block_hash, uint64_t height, struct Buffer *err);

void submit_next_validator_set(struct Buffer val_set, uint64_t height, struct Buffer *err);

/**
 * ECALL: Sets the implicit hash in the enclave.
 * Expects a Buffer containing exactly 32 bytes.
 * On error, sets the error via the provided `err` parameter.
 */
void set_implicit_hash(struct Buffer hash, struct Buffer *err);

/**
 * ECALL: Retrieves the stored implicit hash from the enclave.
 * Returns a Buffer containing 32 bytes.
 * If an error occurs, sets the error via the provided `err` parameter and returns a default Buffer.
 */
struct Buffer get_implicit_hash(struct Buffer *err);

struct Buffer allocate_rust(const uint8_t *ptr, uintptr_t length);

void free_rust(struct Buffer buf);
